version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hispmd_system
    volumes:
      - ./ai:/var/www/html/ai
      - ./analytics:/var/www/html/analytics
      - ./api:/var/www/html/api
      - ./app:/var/www/html/app
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./config:/var/www/html/config
      - ./.env:/var/www/html/.env
      - ./index.php:/var/www/html/index.php
      - ./LICENSE:/var/www/html/LICENSE
      - ./map_files:/var/www/html/map_files
      - ./mysql-init:/var/www/html/mysql-init
      - ./README.md:/var/www/html/README.md
      - ./server.html:/var/www/html/server.html
      - ./src:/var/www/html/src
      - ./styles:/var/www/html/styles
      - ./test:/var/www/html/test
      - ./test.php:/var/www/html/test.php
      - ./vendor:/var/www/html/vendor
    expose:
      - "9000"
      - "8501"
    depends_on:
      - db
    networks:
      - hispmdnet

  nginx:
    image: nginx:latest
    container_name: hispmd_nginx
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ai:/var/www/html/ai
      - ./analytics:/var/www/html/analytics
      - ./api:/var/www/html/api
      - ./app:/var/www/html/app
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./config:/var/www/html/config
      - ./.env:/var/www/html/.env
      - ./index.php:/var/www/html/index.php
      - ./LICENSE:/var/www/html/LICENSE
      - ./map_files:/var/www/html/map_files
      - ./mysql-init:/var/www/html/mysql-init
      - ./README.md:/var/www/html/README.md
      - ./server.html:/var/www/html/server.html
      - ./src:/var/www/html/src
      - ./styles:/var/www/html/styles
      - ./test:/var/www/html/test
      - ./test.php:/var/www/html/test.php
      - ./vendor:/var/www/html/vendor
    depends_on:
      - php
    networks:
      - hispmdnet

  metabase:
    image: metabase/metabase:v0.50.12
    container_name: hispmd_viz
    hostname: metabase
    volumes:
      - hispmd_vizdata:/metabase-data
    ports:
      - "4004:3000"
    environment:
      MB_DB_FILE: /metabase-data/hispmd.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: hispmddb
      MB_DB_PORT: 5432
      MB_DB_USER: hispmddb
      MB_DB_PASS: hispmddb
      MB_DB_HOST: postgres
      MB_ADMIN_EMAIL: dev@merqconsultancy.org
      MB_ADMIN_FIRST_NAME: MERQ
      MB_ADMIN_PASSWORD: hispmdmerqdev0
    depends_on:
      - postgres
    networks:
      - hispmdnet

  postgres:
    image: postgres:latest
    container_name: hispmd_postgres
    hostname: postgres
    environment:
      POSTGRES_DB: hispmddb
      POSTGRES_USER: hispmddb
      POSTGRES_PASSWORD: hispmddb
    volumes:
      - ./src/hispmddb:/docker-entrypoint-initdb.d/hispmddb
    networks:
      - hispmdnet

  db:
    image: mariadb:11.2.4
    restart: always
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: hisp_md
      MYSQL_ROOT_PASSWORD: merqhispmdadmin
      MYSQL_USER: hisp_md
      MYSQL_PASSWORD: hisp_md
    volumes:
      - ./src/hispmd_dev.sql:/docker-entrypoint-initdb.d/hispmd_dev.sql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - hispmdnet

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "3308:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: hisp_md
      PMA_PASSWORD: hisp_md
    networks:
      - hispmdnet

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5434:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@merqconsultancy.org
      PGADMIN_DEFAULT_PASSWORD: merqhispmddev
    volumes:
      - hispmd_pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - hispmdnet

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: merqhispmddev
      MONGO_INITDB_ROOT_PASSWORD: merqhispmddev
    volumes:
      - hispmd_mongodata:/data/db
    networks:
      - hispmdnet

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - "8118:8118"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: merqhispmddev
      ME_CONFIG_MONGODB_ADMINPASSWORD: merqhispmddev
      ME_CONFIG_MONGODB_URL: mongodb://merqhispmddev:merqhispmddev@mongo:27017/
    depends_on:
      - mongo
    networks:
      - hispmdnet

volumes:
  hispmd_pgadmindata:
  hispmd_vizdata:
  hispmd_mongodata:

networks:
  hispmdnet:
    driver: bridge
