version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hispmd_system
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.20  # Adjust as needed
    volumes:
      - ./analytics:/var/www/html/analytics
      - ./api:/var/www/html/api
      - ./app:/var/www/html/app
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./config:/var/www/html/config
      - ./.env:/var/www/html/.env
      - ./index.php:/var/www/html/index.php
      - ./LICENSE:/var/www/html/LICENSE
      - ./map_files:/var/www/html/map_files
      - ./mysql-init:/var/www/html/mysql-init
      - ./README.md:/var/www/html/README.md
      - ./server.html:/var/www/html/server.html
      - ./src:/var/www/html/src
      - ./styles:/var/www/html/styles
      - ./test:/var/www/html/test
      - ./test.php:/var/www/html/test.php
      - ./vendor:/var/www/html/vendor
    expose:
      - "9000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: hisp_md
      MYSQL_PASSWORD: hisp_md
      MYSQL_DATABASE: hisp_md

  chat:
    build:
      context: .
      dockerfile: Dockerfile
    image: hispmd_chatbot
    container_name: hispmd_chatbot
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.21  # Adjust as needed
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./ai/chat:/ai/chat
      - ./ai/chat/.env:/ai/chat/.env
      - ./ai/chat/certs:/ai/chat/certs
      - ./ai/chat/.streamlit/config.toml:/root/.streamlit/config.toml
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: hispmd_nginx
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.22  # Adjust as needed
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./analytics:/var/www/html/analytics
      - ./api:/var/www/html/api
      - ./app:/var/www/html/app
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./config:/var/www/html/config
      - ./.env:/var/www/html/.env
      - ./index.php:/var/www/html/index.php
      - ./LICENSE:/var/www/html/LICENSE
      - ./map_files:/var/www/html/map_files
      - ./mysql-init:/var/www/html/mysql-init
      - ./README.md:/var/www/html/README.md
      - ./server.html:/var/www/html/server.html
      - ./src:/var/www/html/src
      - ./styles:/var/www/html/styles
      - ./test:/var/www/html/test
      - ./test.php:/var/www/html/test.php
      - ./vendor:/var/www/html/vendor
    depends_on:
      - php

  metabase:
    image: metabase/metabase:v0.50.12
    container_name: hispmd_viz
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.23  # Adjust as needed
    ports:
      - "4004:3000"
    environment:
      MB_DB_FILE: /metabase-data/hispmd.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: hispmddb
      MB_DB_PORT: 5432
      MB_DB_USER: hispmddb
      MB_DB_PASS: hispmddb
      MB_DB_HOST: postgres
      MB_ADMIN_EMAIL: dev@merqconsultancy.org
      MB_ADMIN_FIRST_NAME: MERQ
      MB_ADMIN_PASSWORD: hispmdmerqdev0
    depends_on:
      - postgres
    volumes:
      - hispmd_vizdata:/metabase-data

  postgres:
    image: postgres:latest
    container_name: hispmd_postgres
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.24  # Adjust as needed
    environment:
      POSTGRES_DB: hispmddb
      POSTGRES_USER: hispmddb
      POSTGRES_PASSWORD: hispmddb
    volumes:
      - ./src/hispmddb:/docker-entrypoint-initdb.d/hispmddb

  db:
    image: mariadb:11.2.4
    container_name: hispmd_sys-db-1
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.25  # Adjust as needed
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: hisp_md
      MYSQL_ROOT_PASSWORD: merqhispmdadmin
      MYSQL_USER: hisp_md
      MYSQL_PASSWORD: hisp_md
    volumes:
      - ./src/hispmd_dev.sql:/docker-entrypoint-initdb.d/hispmd_dev.sql
      - ./mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: hispmd_sys-phpmyadmin-1
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.26  # Adjust as needed
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: hisp_md
      PMA_PASSWORD: hisp_md

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hispmd_sys-pgadmin-1
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.27  # Adjust as needed
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@merqconsultancy.org
      PGADMIN_DEFAULT_PASSWORD: merqhispmddev
    volumes:
      - hispmd_pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres

  mongo:
    image: mongo:latest
    container_name: hispmd_sys-mongo-1
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.28  # Adjust as needed
    environment:
      MONGO_INITDB_ROOT_USERNAME: merqhispmddev
      MONGO_INITDB_ROOT_PASSWORD: merqhispmddev
    volumes:
      - hispmd_mongodata:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: hispmd_sys-mongo-express-1
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.29  # Adjust as needed
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: merqhispmddev
      ME_CONFIG_MONGODB_ADMINPASSWORD: merqhispmddev
      ME_CONFIG_MONGODB_URL: mongodb://merqhispmddev:merqhispmddev@mongo:27017/
    depends_on:
      - mongo

  grafana:
    image: grafana/grafana-enterprise
    container_name: hispmd_grafana
    networks:
      hispmdnet:
        ipv4_address: 192.168.112.30  # Adjust as needed
    ports:
      - "3030:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  hispmd_pgadmindata:
  hispmd_vizdata:
  hispmd_mongodata:
  grafana-storage:

networks:
  hispmdnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.112.0/24
