#version: '3.8'

services:
  chat:
    image: hispd_chatbot  # Specify the Docker image name
    container_name: HISPD_ChatBot  # Specify the Docker container name
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./chat:/chat
      - ./chat/certs:/ai/chat/certs  # Mount the SSL certificates directory
      - ./chat/.streamlit/config.toml:/root/.streamlit/config.toml  # Mount the config.toml file
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SSH_USE=${SSH_USE}
      - SSH_HOST=${SSH_HOST}
      - SSH_PORT=${SSH_PORT}
      - SSH_USER=${SSH_USER}
      - SSH_PASSWORD=${SSH_PASSWORD}
      - LOCAL_PORT=${LOCAL_PORT}
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - ./chat/.env  # Specify the path to your .env file
    networks:
      - hispd_chatbot

networks:
  hispd_chatbot:
    driver: bridge
